#!/usr/bin/with-contenv bash

exec 2>&1

# shellcheck disable=SC2153 disable=SC2154
if [[ -n "${AUTH}" ]]; then
  auth="--auth ${AUTH}"
fi

# shellcheck disable=SC2086
exec s6-setuidgid abc /usr/bin/darkhttpd /ariang ${auth} \
  --addr 0.0.0.0 \
  --port 8080 \
  --log /dev/null \
  --no-listing
