---

name: Build Docker Image

'on':
  repository_dispatch:
    types: [build]

jobs:
  build-rolling:
    name: Build "rolling" Image
    if: ${{ github.event.client_payload.is_tag == false && github.event.client_payload.branch_name == 'master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date and time
        shell: bash
        run: echo "##[set-output name=timestamp;]$(date --rfc-3339=seconds)"
        id: timestamp
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            BUILD_DATE=${{ steps.timestamp.outputs.timestamp }}
            BUILD_REF=${{ github.event.client_payload.ref }}
            BUILD_VERSION=rolling
          push: true
          tags: danie1k/aria2-ariang:rolling

  build-latest:
    name: Build "latest" Image
    if: ${{ github.event.client_payload.is_tag == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date and time
        shell: bash
        run: echo "##[set-output name=timestamp;]$(date --rfc-3339=seconds)"
        id: timestamp
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            BUILD_DATE=${{ steps.timestamp.outputs.timestamp }}
            BUILD_REF=${{ github.event.client_payload.ref }}
            BUILD_VERSION=${{ github.event.client_payload.tag_name }}
          push: true
          tags: danie1k/aria2-ariang:latest

  build-release:
    name: Build release Image
    if: ${{ github.event.client_payload.is_tag == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date and time
        shell: bash
        run: echo "##[set-output name=timestamp;]$(date --rfc-3339=seconds)"
        id: timestamp
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            BUILD_DATE=${{ steps.timestamp.outputs.timestamp }}
            BUILD_REF=${{ github.event.client_payload.ref }}
            BUILD_VERSION=${{ github.event.client_payload.tag_name }}
          push: true
          tags: danie1k/aria2-ariang:${{ github.event.client_payload.tag_name }}
